repos:
- repo: https://github.com/dnephin/pre-commit-golang
  rev: v0.5.1
  hooks:
  - id: go-fmt
    exclude: templates/
  - id: go-vet
    exclude: templates/
  - id: go-lint
    exclude: templates/
