{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "mimir-rules-controller.fullname" . }}
  labels:
    {{- include "mimir-rules-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "mimir-rules-controller.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "mimir-rules-controller.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
