apiVersion: rulescontroller.k8s.healthjoy.com/v1alpha1
kind: MimirRule
metadata:
  name: example-mimirrule
  namespace: default
spec:
  groups:
  - name: example-mimirrule
    rules:
    - alert: example-mimirrule
      expr: 1
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: example-mimirrule
        description: example-mimirrule